force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
        <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <fields>
        <fullName>Institution_Name__c</fullName>
        <label>Institution Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Field_of_Study__c</fullName>
        <label>Field of Study</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>GPA__c</fullName>
        <label>GPA</label>
        <type>Number</type>
        <precision>3</precision>
        <scale>2</scale>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
        <picklist>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teamwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem Solving</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <label>Certification Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Issuing_Organization__c</fullName>
        <label>Issuing Organization</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <label>Earned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkedIn_Profile__c</fullName>
        <label>LinkedIn Profile</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Portfolio_Website__c</fullName>
        <label>Portfolio/Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <type>MultiselectPicklist</type>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>Awards_Achievements__c</fullName>
        <label>Awards/Achievements</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/No_Longer_Interested__c.field-meta.xml
<CustomField>
    <fullName>No_Longer_Interested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>this is the checkbox that defines that whether the candidate is interested or not</description>
    <inlineHelpText>this is the checkbox that defines that whether the candidate is interested or not</inlineHelpText>
    <label>No Longer Interested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationStatusUpdateHandlerTest.cls
/**
 * @description       : Test class for JobApplicationStatusUpdateHandler
 * @author            : Indrajit Pal
 * @last modified on  : 12-26-2024
 * @last modified by  : Indrajit Pal
**/
@isTest
public with sharing class JobApplicationStatusUpdateHandlerTest {
    /**
    * @description This is the test setup method for RunAs User
    * @author Indrajit Pal | 12-26-2024 
    **/
    @TestSetup
    static void makeData(){
        User adminUser = CommonTestHelper.createUserWithProfile('System Administrator', 'testuser@example.com', 'randuser');
        Database.insert(adminUser);
        Candidate__c candidateObj = CommonTestHelper.createCandidateWithoutContact('Indrajit', 'Pal', 'example@email.com');
        candidateObj.No_Longer_Interested__c = true;
        insert candidateObj;

        Job_Application__c jobApplicationObj = CommonTestHelper.createJobApplication(candidateObj);
        jobApplicationObj.Status__c = 'Applied';
        DateTime myDateTime = DateTime.newInstance(2023, 8, 21, 14, 30, 0);
        jobApplicationObj.Job_Interview_Date__c = myDateTime;
        insert jobApplicationObj;
    }

    /**
    * @description This is the method of the test class for the batch class where the status of the job application is changed to Withdrawn.
    * @author Indrajit Pal | 12-26-2024 
    **/
    @isTest
    public static void markWithdrawnIfUninterestedTest(){
        User testingUser = CommonTestHelper.findUserWithEmail('testuser@example.com');
        List<Job_Application__c> jobApllicationList = [SELECT Id,
                                                            Status__c,
                                                            candidate__r.no_longer_interested__c,
                                                            Job_Interview_Date__c,
                                                            LastModifiedDate
                                                        FROM Job_Application__c
                                                        WHERE candidate__r.no_longer_interested__c = true];
        Test.startTest();
            System.runAs(testingUser){
                JobApplicationStatusUpdateHandler.updateJobApplicationStatus(jobApllicationList);
            }
        Test.stopTest();
        List<Job_Application__c> updateJobApllicationList = [SELECT id,
                                                                    Status__c,
                                                                    candidate__r.no_longer_interested__c,
                                                                    LastModifiedDate
                                                                FROM Job_Application__c
                                                                WHERE id =:jobApllicationList[0].id];
        System.assertEquals('Withdrawn', updateJobApllicationList[0].Status__c, 'The status must be changed to WITHDRAWN');
    }

    /**
    * @description This is the method for the batch class where the status of the job application is changed to Not Selected.
    * @author Indrajit Pal | 12-26-2024 
    **/
    @isTest
    public static void updateStatusToNotSelectedTest(){
        User testingUser = CommonTestHelper.findUserWithEmail('testuser@example.com');
        List<Candidate__c> candidateList = [SELECT  id,
                                                    no_longer_interested__c
                                                FROM Candidate__c
                                                WHERE Email__c = 'example@email.com'];
        candidateList[0].no_longer_interested__c = false;
        update candidateList;
        List<Job_Application__c> jobApllicationList = [SELECT id,
                                                            Status__c,
                                                            candidate__r.no_longer_interested__c,
                                                            Job_Interview_Date__c,
                                                            LastModifiedDate
                                                        FROM Job_Application__c
                                                        WHERE candidate__r.no_longer_interested__c = false];
        
        jobApllicationList[0].Status__c = 'Interviewed';
        jobApllicationList[0].Job_Interview_Date__c = DateTime.now().addDays(-15);
        update jobApllicationList;
        Test.startTest();
            System.runAs(testingUser){
                JobApplicationStatusUpdateHandler.updateJobApplicationStatus(jobApllicationList);
            }
        Test.stopTest();
        List<Job_Application__c> updateJobApllicationList = [SELECT id,
                                                                    Status__c,
                                                                    candidate__r.no_longer_interested__c,
                                                                    LastModifiedDate
                                                                FROM Job_Application__c
                                                                WHERE id =:jobApllicationList[0].id];
        System.assertEquals('Not Selected', updateJobApllicationList[0].Status__c,'Assert Failed');
    }
}