force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
        <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <fields>
        <fullName>Institution_Name__c</fullName>
        <label>Institution Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Field_of_Study__c</fullName>
        <label>Field of Study</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>GPA__c</fullName>
        <label>GPA</label>
        <type>Number</type>
        <precision>3</precision>
        <scale>2</scale>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
        <picklist>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teamwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem Solving</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <label>Certification Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Issuing_Organization__c</fullName>
        <label>Issuing Organization</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <label>Earned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkedIn_Profile__c</fullName>
        <label>LinkedIn Profile</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Portfolio_Website__c</fullName>
        <label>Portfolio/Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <type>MultiselectPicklist</type>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>Awards_Achievements__c</fullName>
        <label>Awards/Achievements</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateResumeControllerTest.cls
/**
* @description                : This is the test class for CandidateResumeController
* @author                     : Indrajit Pal
* @last modified on           : 12-28-2024
* @last modified by           : Indrajit Pal
**/
@isTest
public with sharing class CandidateResumeControllerTest {

    /**
    * @description Creates test data for RunAs User
    * @author Indrajit Pal | 12-26-2024 
    **/
    @TestSetup
    static void makesData() {
        User adminUser = CommonTestHelper.createUserWithProfile('System Administrator', 'testuser@example.com', 'randuser');
        Database.insert(adminUser);
        Candidate__c candidateObj = CommonTestHelper.createCandidateWithoutContact('Test', 'example', 'test@example.com');
        candidateObj.Status__c = 'Approved';
        insert candidateObj;
    }
    
    @isTest
    /**
    * @description : This is used to test the main method of the CandidateResumeController class
    * @author Indrajit Pal | 20-12-2024
    **/
    private static void generateResumeTest() {
        User user = [SELECT Id FROM User LIMIT 1];
        System.runAs(user) {
            Test.startTest();
            Candidate__c candidateObj = [SELECT Id, 
                                            First_Name__c, 
                                            Last_Name__c 
                                        FROM Candidate__c LIMIT 1];
            String result = CandidateResumeController.generateResume('[{"appid":"' + candidateObj.Id + '"}]');
            System.assertEquals('Resume Attached Successfully for ' + candidateObj.First_Name__c + ' ' + candidateObj.Last_Name__c + ' ' + '\n', result, 'The result should be a success message.');
            
            List<AsyncApexJob> jobList = [SELECT Id,
                                                Status,
                                                JobItemsProcessed,
                                                TotalJobItems
                                            FROM AsyncApexJob
                                            WHERE ApexClass.Name = 'GenerateCandidateResumesQueueable'
                                            AND Status = 'Queued'];
 
            System.assertNotEquals(0, jobList.size(), 'The job should be enqueued.');
            System.assertEquals('Queued', jobList[0].Status, 'The job should have a status of Queued.');
            Test.stopTest();
        }
    }

    @isTest
    /**
    * @description : This is used to test the main method of the CandidateResumeController class
    * @author Indrajit Pal | 20-12-2024
    **/
    private static void generateResumeNotEligibleTest() {
        User user = [SELECT Id FROM User LIMIT 1];
        System.runAs(user) {
            Test.startTest();
            Candidate__c candidateObj = [SELECT Id, 
                                            First_Name__c, 
                                            Last_Name__c 
                                        FROM Candidate__c LIMIT 1];
            candidateObj.Status__c = 'New';
            Database.update(candidateObj);
            String result = CandidateResumeController.generateResume('[{"appid":"' + candidateObj.Id + '"}]');
            System.assertEquals(candidateObj.First_Name__c + ' ' + candidateObj.Last_Name__c + ' is not Eligible for Resume Generation. '  + '\n', result, 'The result should be an error message.');
            Test.stopTest();
        }
    }

    @isTest
    static void testControllerInitialization() {
        User user = [SELECT Id FROM User LIMIT 1];
        System.runAs(user) {
            Candidate__c candidateObj = [SELECT Id FROM Candidate__c LIMIT 1];
            Test.setCurrentPage(Page.CandidateResumePage);
            ApexPages.currentPage().getParameters().put('Id', candidateObj.Id);

            CandidateResumeController controller = new CandidateResumeController();
            System.assertNotEquals(null, controller.currentUser, 'Current user should be set.');
        }
    }
}