force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions.</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
        <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Job_Title__c</fullName>
        <label>Job Title</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <fields>
        <fullName>Institution_Name__c</fullName>
        <label>Institution Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Field_of_Study__c</fullName>
        <label>Field of Study</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>GPA__c</fullName>
        <label>GPA</label>
        <type>Number</type>
        <precision>3</precision>
        <scale>2</scale>
    </fields>
    <fields>
        <fullName>Skills__c</fullName>
        <label>Skills</label>
        <type>MultiselectPicklist</type>
        <picklist>
            <picklistValues>
                <fullName>Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teamwork</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Problem Solving</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>Certification_Name__c</fullName>
        <label>Certification Name</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Issuing_Organization__c</fullName>
        <label>Issuing Organization</label>
        <type>Text</type>
        <length>255</length>
    </fields>
    <fields>
        <fullName>Earned_Date__c</fullName>
        <label>Earned Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LinkedIn_Profile__c</fullName>
        <label>LinkedIn Profile</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Portfolio_Website__c</fullName>
        <label>Portfolio/Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Languages__c</fullName>
        <label>Languages</label>
        <type>MultiselectPicklist</type>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>French</fullName>
            </picklistValues>
        </picklist>
    </fields>
    <fields>
        <fullName>Awards_Achievements__c</fullName>
        <label>Awards/Achievements</label>
        <type>LongTextArea</type>
        <length>32000</length>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoGenerateResumeTriggerHandler.cls
/**
 * @description       : This is the handler class for the trigger -> AutoGenerateResumeTrigger
 * @author            : Indrajit Pal
 * @last modified on  : 12-26-2024
 * @last modified by  : Indrajit Pal
**/
public inherited sharing class AutoGenerateResumeTriggerHandler extends ExtendedTriggerHandler{
    private List<Job_Application__c> newJobApplicationList;
    private Map<Id, Job_Application__c> jobAppIdVsJobAppOldMap;

    /**
    * @description Constructor which contains all the default trigger variables which 
                   are in use.
    * @author Indrajit Pal | 12-26-2024 
    **/
    public AutoGenerateResumeTriggerHandler(){
        this.newJobApplicationList = (List<Job_Application__c>) Trigger.new;
        this.jobAppIdVsJobAppOldMap = (Map<Id, Job_Application__c>) Trigger.oldMap;
    }

    /**
    * @description After update it will check for the old status of the job application and
                   the new status, then if the status is 'Schedule Interviews' then it will 
                   generate resume and attach it to the candidate object.
    * @author Indrajit Pal | 12-26-2024 
    **/
    public override void afterUpdate(){
        Set<Id> candidateIdsToProcessList = new Set<Id>();

        try{
            // Sort the Job Application ids where status is updated to 'Schedule Interviews'
            for(Job_Application__c newJobApplicationObj : newJobApplicationList){
                Job_Application__c oldJobAppObj = jobAppIdVsJobAppOldMap.get(newJobApplicationObj.Id);
                if((newJobApplicationObj.Status__c == RecruitingAppCustomConstants.JOB_APPLICATION_STATUS_SCHEDULE_INTERVIEW) 
                    && (oldJobAppObj.Status__c != RecruitingAppCustomConstants.JOB_APPLICATION_STATUS_SCHEDULE_INTERVIEW)){
                    candidateIdsToProcessList.add(newJobApplicationObj.Candidate__c);
                }
            }
            if(!candidateIdsToProcessList.isEmpty()){
                System.enqueueJob(new GenerateCandidateResumesQueueable(new List<Id>(candidateIdsToProcessList)));
            }
            else{
                throw new CustomException(RecruitingAppCustomConstants.AUTO_RESUME_GENERATE_TRIGGER_HANDLER_ERROR_MESSAGE);
            }
        } catch (Exception exObj){
            CustomExceptionHandler.logException(exObj, AutoGenerateResumeTriggerHandler.class.getName());
        }
    }
}